cerebral/overmind

- packages/node_modules/overmind/package.json
This will ensure that `parcel` correctly identifies the code we ship in `lib`/`es` and transpile it if needed.
> chore(overmind): add `engines.browsers` so parcel correctly works

- packages/node_modules/proxy-state-tree/src/index.test.ts
- packages/node_modules/proxy-state-tree/src/proxify.ts
As discussed on discord. Throwing when parts of the state tree is nested in the state. 
For mutating functions on the array proxy I choose to just see if any value is proxied and reject the insertion.  The solution for the mutating function on the array is not optimal. There should maybe be another list of mutating functions that insert a value. Currently I check every argument for all mutating functions.
There is also quite a lot of duplication in these code paths. Maybe these need to be refactored (would reduce file size too)
> feat(proxy-state-tree): don't allow nesting proxies in state tree

- packages/node_modules/overmind/src/Action.ts
- packages/node_modules/overmind/src/index.test.ts
- packages/overmind-website/api/action.md
BREAKING CHANGE:
any returned promise from a do operator will now hold action execution until resolved
> feat(overmind): allow do operator to return promise

- packages/node_modules/action-chain/src/utils.ts
If a effect had an array property, both the `if` and `else if` were false and the Proxy was returning `undefined`
> fix(action-chain): add fall through in effect proxying

- packages/node_modules/proxy-state-tree/src/proxify.ts
Just cleaned up the implementation a bit.
> refactor(proxy-state-tree): extracted error message into functions to reduce repetition

- packages/node_modules/overmind/src/index.ts
this avoids bugs when some parts of a configuration state are reused
> fix(overmind): deep clone state on app creation

- packages/node_modules/overmind/src/index.test.ts
- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/modules.ts
this greatly simplifies the types
BREAKING CHANGE:
modules are now supported by the "modules" function
Replaces PR #102 
```ts
const config = modules({
state: {...},
actions: {...},
modules {
foo: {...},
bar: {...},
}
})
```
> fix(overmind): extract modules into its own function

- packages/node_modules/proxy-state-tree/src/index.ts
This is useful for libraries doing introspection (in testing, storybook display, error handling).
> feat(proxy-state-tree): export PATH so that external libraries can us it

- packages/node_modules/overmind/src/index.test.ts
- packages/node_modules/overmind/src/index.ts
Passing an object as argument to an action is a common pattern and we should allow passing part of the state tree and have tracking/mutations work there:
```html
<Field form={app.state.form.login} key="username" />
```
```ts
app.actions.form.changeValue({form, key, value}) // form and key are props
```
> feat(overmind): allow proxies in object value passed to action

- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/internalTypes.ts
- packages/node_modules/overmind/src/types.ts
This fixes these error messages:
```
(12,140): Type 'App' does not satisfy the constraint 'BaseApp'.
Type 'Overmind<Configuration>' is not assignable to type 'BaseApp'.
Types of property 'state' are incompatible.
Type 'ResolveState<{}> | undefined' is not assignable to type '{}'.
Type 'undefined' is not assignable to type '{}'.
```
> fix(overmind): fix actions type resolution when actions are missing in config

- packages/node_modules/overmind-devtools/src/app/index.ts
- packages/node_modules/overmind-devtools/src/app/operators.ts
- packages/node_modules/overmind-react/src/index.test.tsx
- packages/node_modules/overmind/src/derived.test.ts
- packages/node_modules/overmind/src/index.test.ts
- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/internalTypes.ts
- packages/node_modules/overmind/src/reaction.test.ts
- packages/node_modules/overmind/src/types.ts
> refactor overmind to simplify exposed types, use Config instead of App

- packages/node_modules/overmind-devtools/src/app/actions.ts
- packages/node_modules/overmind-devtools/src/app/effects.ts
- packages/node_modules/overmind/src/index.test.ts
- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/types.ts
This is the only way for advance uses of this important initialization step, like connecting components in configurations.
It's really the only moment in the whole app lifetime that the modules get to have access to the app itself and there really are some legitimate and important use cases. Just passing the actions does not cut it.
> fix(overmind): use the full and complete app for onInitialize

- packages/node_modules/overmind/src/internalTypes.ts
Without this fix, `ResolveState` never resolves the TDerive types because of a circular definition 
TDerive uses ResolveState which uses TDerive
> fix(overmind): fix ResolveState to avoid circular definition of TDerive

- packages/node_modules/overmind/src/types.ts
It is useful to type helper functions in actions and components.
> fix(overmind): add TApp type back

- packages/node_modules/overmind-react/src/index.ts
Create hook was setting the initial state to null and then updating with an effect. This caused a number of issues.
1. The tidy up effect would never work due to being created in the first render and not being updated (closure bug).
2. Every computed using the overmind would always render twice.
3. Due to 1. react would complain of memory leaks.
4. Any components using overmind state to configure internal useState (eg with forms) would get an initial value of null and then never update (due to the way that useState works.
> fix(overmind-react): refactor createHook with component lifecycle fixes

- packages/node_modules/overmind/src/index.ts
My localhost app kept trying to connect to the  devtools even when options.devtools were set in false.
* I expect that when devtools is false we don't try to initialize the debugger.
* No options default to empty object, this will still try to connect to the default devTools in localhost unless options.devtools is a false boolean
Seems to be a simple boolean operator typo.
> false devtools shouldn't try to initializeDevtools

- packages/node_modules/overmind/src/index.ts
I extracted all the resolution logic for `host` and `name` from `initializeDevtools` to have them in one place.
> use `options.name` as name if provided

- packages/node_modules/proxy-state-tree/src/Proxyfier.ts
This avoids the following error:
```
../../../../node_modules/proxy-state-tree/lib/Proxyfier.d.ts(14,56): error TS2307: Cannot find module 'proxy-state-tree/src/types'.
```
> fix(proxy-state-tree): fix function to avoid breaking types being exported

- packages/node_modules/overmind/src/types.ts
If the Config has `null` or `undefined` as possible values for keys, the object is not seen as a TStateObject and prevents derived from being resolved in this object.
This allows `null` and `undefined` values.
> fix(overmind): fix TStateObject types so that resolve works 

- packages/overmind-website/examples/guide/routing/tab.ts
showUsersPage() is part of a `parallel()` operator pipeline so needs to be wrapped in an `action()` operator
incidentally I created a codesandbox demo of for the routing tutorial.
here is the bug in action: https://codesandbox.io/s/mzmq42wjq9
here is the fix: https://codesandbox.io/s/github/100ideas/overmind-routing-demo/tree/codesandbox_v1
> wrap showUsersPage() in action() so it works w/ parallel()

- packages/node_modules/overmind-react/src/index.ts
To avoid storing the tracking tree in an object an updating that object by creating a new object every mutation (even in production) use `useForceRerender` to just toggle a boolean.
> refactor(overmind-react): use useRef for storing componentId and tracking tree

- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/types.ts
to make IContext compatible with react hooks and component types.
```ts
const ctx = useOvermind()
function foo(ctx: IContext<Config, undefined>) {} // Here `value` is expected but
foo(ctx) // Not compatible: Property 'value' is missing in type...
```
> fix(overmind): use a temporary action context

- packages/overmind-website/api/overmind.md
As far as I understand config.name is not only for better developer tools support but also to differentiate the state and actions for overmind. 
Here you can see what I mean:
https://codesandbox.io/s/kxykm17pz5
> Update options.name docs

- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/internalTypes.ts
- packages/node_modules/overmind/src/mock.test.ts
- packages/node_modules/overmind/src/ssr.test.ts
- packages/node_modules/overmind/src/utils.ts
- packages/node_modules/proxy-state-tree/src/index.ts
This will allow for a safe version of Overmind to instantiate on every request on the server to produce state for hydration and rehydration on the client. It works like this:
```js
// SERVER
(req, res) => {
// Create instance, can reuse config as it is deeply copied
const overmind = createOvermindSSR(config)
// Just change the state of it
overmind.state.foo = "bar2"
// Render the app
const html = renderToString(<Provider value={overmind}><App /></Provider>)
// Produce a result
res.send(`
<html>
<head></head>
<body>
<div id="app">{html}</div>
<script>
window.__OVERMIND = ${JSON.stringify(overmind.hydrate())}
</script>
<script src="app.js"></script>
</body>
</html>
`)
}
// CLIENT
const onInitialize = ({ state }, overmind) => {
overmind.rehydrate(state, window.__OVERMIND)
}
```
What is …
> feat(overmind): server Side Rendering

- packages/overmind-website/examples/guide/routing/setup.ts
All other examples use `showHomePage` etc., instead of `routeHomePage`.
> Use same action names as in the other examples

- packages/overmind-website/api/overmind.md
One change is a typo and the other tries to be more direct in telling that Add Mutation Listener executes the function before the mutation is executed.
> Small changes in overmind api docs

- packages/node_modules/overmind/src/index.test.ts
- packages/node_modules/overmind/src/utils.test.ts
- packages/node_modules/overmind/src/utils.ts
The previous implementation would take `{ get x() { return 123 } }` and return `{ x: 123 }` which resulted in problems when I was trying to run tests with createOvermindMock because all calculations based on this, were no longer recalculated
> Fix deepCopy to pass getters to cloned object

- packages/overmind-website/examples/guide/runningsideeffects/object.ts
The name of this export should be `api` (as it is with the TypeScript example).
> Fix incorrect export name

- packages/node_modules/overmind/src/config/index.ts
I noticed that I could merge state, actions and effects that had properties with the same names. One set will just get overwritten in the .reduce() of the config.merge function. I have therefore thrown an error should the merge function encounter any duplicates.
> FIX Throw error during merge if encounter duplicate keys

- packages/node_modules/overmind/src/internalTypes.ts
Resolving actions that don't exist to either `never` or `undefined` won't prevent calling them or passing them as parameters. But resolving them as `unknown` will do so.
> Resolve unknown actions as such

- package-lock.json
- package.json
- packages/node_modules/overmind-devtools-client/DevtoolBackend.js
- packages/node_modules/overmind-devtools-client/src/BackendConnector.ts
- packages/node_modules/overmind-devtools-vscode/.gitignore
- packages/node_modules/overmind-devtools-vscode/.vscodeignore
- packages/node_modules/overmind-devtools-vscode/CHANGELOG.md
- packages/node_modules/overmind-devtools-vscode/README.md
- packages/node_modules/overmind-devtools-vscode/devtoolsDist/index.html
- packages/node_modules/overmind-devtools-vscode/package.json
- packages/node_modules/overmind-devtools-vscode/src/DevtoolsPanel.ts
- packages/node_modules/overmind-devtools-vscode/src/extension.ts
- packages/node_modules/overmind-devtools-vscode/src/index.ts
- packages/node_modules/overmind-devtools-vscode/src/utils/Logger.ts
- packages/node_modules/overmind-devtools-vscode/tsconfig.json
- packages/node_modules/overmind-devtools-vscode/vsc-extension-quickstart.md
**Heads up: WIP**
Opening this for discussion and input.
If you want to play around with this, open `overmind-devtools-vscode` in VS Code and press run. This will start the `Extension Development Environment`. Open command palette (osx: cmd + shift + p) and search for `overmind`. This should open the extension and show the `Waiting for an app to connect...` screen.
Fire up any overmind-app that connects to devtools on port 3031. This should bring up the devtools, and any actions taken in the app should be reflected.
**Known issues:**
- Relaunch does not work. 
- overmind-devtools-client dist files are manually copied into overmind-devtools-vscode
- storage in overmind-devtools-vscode is a dummy, and must be updated to VSCode APIs …
> WIP: VS Code extension

- packages/overmind-website/examples/guide/getstarted/connectapp.ts
Gives error: `Attempted import error: 'config' is not exported from './overmind'.`
> Export config from index.ts

- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/operator.ts
- packages/node_modules/overmind/src/utils.ts
I noticed while reading the overmind code that the `IS_PRODUCTION` and `IS_DEVELOPMENT` checks where moved to the utils file. 
As a consequence webpack isn't able to strip the development stuff in production anymore because it can't currently resolve these kinds of dependencies. 
Just to see how much of an impact this has I moved all these checks back into the places `IS_PRODUCTION` and `IS_DEVELOPMENT` where used 
and tested with a minimal production build:
```js
import { Overmind } from 'overmind'
window.app = new Overmind({})
```
```js
const path = require('path')
const TerserPlugin = require('terser-webpack-plugin')
module.exports = {
mode: 'production',
entry: path.resolve('index.js'),
output: {
path: path.resolve('dist'),
filename: 'bundle.js',
},
optimization: {
minimizer: [
new …
```
> Reduce production bundle size by 1/3

- packages/node_modules/overmind/src/Devtools.ts
- packages/node_modules/overmind/src/index.ts
We might not want this but I was done with it anyways. 
Removing the devtools from a production build is resulting in a little drop in bundle size too. 
Before: `17.9 KiB` (`5.39 KiB` gzip)
After: `16.2 KiB` (`4.81 KiB` gzip)
Not a huge drop like before but still ~9% (~10% gzip) size improvements. 
>I also removed the `throttle` function from `Devtools.ts` because it was unused but that got stripped away by webpack before
so there was no bundle size gain
> perf(overmind): completely remove devtools in production

- package-lock.json
- package.json
- packages/node_modules/overmind-devtools-client/package.json
- packages/node_modules/overmind-devtools-client/webpack.prod.js
While we are at it. I did another pass optimising the bundle size of the devtools-client. Before you still had 
`inline-source-maps` turned on in productions. I disabled that know and the bundle size 
dropped from `2.91 MiB` to `238 KiB`.
> removed inline-source-maps from production build of devtools-client

- package-lock.json
- package.json
- packages/node_modules/overmind/package.json
- packages/node_modules/overmind/webpack.config.js
In light of my recent finding regarding the bundle size (#294) of overmind, I think it is a good idea to add [bundlesize](https://github.com/siddharthkp/bundlesize). 
To get it working I added a new minified production build of overmind to `dist/overmind.min.js` using webpack. Currently the limit is set to `10kb` (gzip) we are currently at ~6kb so should be fine for know.
We could even have travis do a ping back of the bundlesize using [this](https://github.com/siddharthkp/bundlesize)
> create a prod build and add bundlesize to keep an eye on the size

- packages/node_modules/overmind/src/index.ts
- packages/node_modules/overmind/src/operators.test.ts
Difference between the **throttle** and **debounce** operators:
The **throttle** operator executes the "next" path at most every x [ms].
The **debounce** operator executes the "next" path x [ms] after the last call.
If there is a very long delay (say 30 seconds), and calls keep coming every few seconds, **debounce** would never execute the next statements whereas **throttle** would execute every 30 seconds.
@christianalfoni Please review the code as it is based on debounce and I am not sure about the "next" call inside the timeout or what the "final" thing is.
> feat(overmind): add throttle operator

- packages/overmind-website/guides/beginner/01_quickstart.md
- packages/overmind-website/guides/beginner/02_getstarted.md
- packages/overmind-website/guides/beginner/03_definingstate.md
- packages/overmind-website/guides/beginner/04_writingapplicationlogic.md
- packages/overmind-website/guides/beginner/05_runningsideeffects.md
- packages/overmind-website/guides/beginner/06_typescript.md
- packages/overmind-website/guides/beginner/07_structuringtheapp.md
- packages/overmind-website/guides/beginner/08_connectingcomponents.md
- packages/overmind-website/guides/beginner/09_usingovermindwithreact.md
- packages/overmind-website/guides/beginner/10_usingovermindwithangular.md
- packages/overmind-website/guides/beginner/11_usingovermindwithvue.md
- packages/overmind-website/guides/intermediate/01_managinglists.md
- packages/overmind-website/guides/intermediate/02_routing.md
- packages/overmind-website/guides/intermediate/04_goingfunctional.md
- packages/overmind-website/guides/intermediate/05_writingtests.md
- packages/overmind-website/guides/pro/01_serversiderendering.md
- packages/overmind-website/guides/pro/02_createcustomoperators.md
As I read through the Overmind guide, I thought I'd make little spelling corrections and tweak the text for a bit more fluency as I go. These are really mostly simple corrections and occasional rewordings. :)
- In the Vue section I specifically noticed there were some duplicated paragraphs, so it's probably a good idea to double-check I didn't mess up anything.
- I noticed `overmind-website/examples/guide/serversiderendering/renderonserver.ts` didn't get rendered in the SSR guide, wonder if there's a syntax error? Didn't examine deeper in this PR, though.
> Spell-check and tweak the guide for fluency

- packages/node_modules/proxy-state-tree/package.json
- packages/node_modules/proxy-state-tree/src/Proxyfier.ts
- packages/node_modules/proxy-state-tree/src/index.test.ts
- packages/node_modules/proxy-state-tree/webpack.config.js
Some stuff in this PR:
* fixed the second argument to indexOf and adding a test for it too 
* create a release bundle similar to overmind and tests it's size, size budget is 3KB (gzip) for now (that is currently ~50% of overmind). 
* removed the dev messages in production (saves 0,25KB gzip) and optimised the calling of methods by not having to go though a `.map` call on all arguments.
> State tree improvements

- packages/node_modules/overmind/src/index.ts
I got this error when I forgot to mock out an effect.
> Fix typo in error message from overmind mock

- packages/node_modules/overmind/src/config/statechart.ts
only send to devtools if there devtools has been initialized
I was setting up an overmind store and using `statechart` in an mdx-deck project which when setting up overmind, it does not reach the `initializeDevtools` step and `statechart` errors.
> check for devtools presence in statechart

- packages/overmind-website/examples/guide/writingtests/actionsnapshot.ts
- fix `=` in object to `:` in writing tests docs
> fix syntax on writing tests guide

- packages/node_modules/overmind-graphql/package.json
Add missing TS types for overmind-graphql. 
It's for solving this error:
```
ERROR in node_modules/overmind-graphql/lib/index.d.ts(2,41):
TS7016: Could not find a declaration file for module 'phoenix'. 'node_modules/phoenix/priv/static/phoenix.js' implicitly has an 'any' type.
Try `npm install @types/phoenix` if it exists or add a new declaration (.d.ts) file containing `declare module 'phoenix';`
Version: typescript 3.8.3, eslint 6.8.0
```
> Fix overmind-graphql missing TS types

- packages/node_modules/overmind-react/src/index.ts
This change makes it so we no longer have to use `createHook<typeof config>()`, as long as `Config`
declaration is overriden we can just do `createHook()`.
> fix(overmind-react): set default config type for hooks and connects

- packages/node_modules/overmind/src/internalTypes.ts
@christianalfoni I may have seriously misunderstood the typing, but it looks like `IContext` was replaced with a shell of `IContext` to avoid circular issues. This seems like a good place to do that, however, the entire IContext has to be matched. Add the missing (and new) IContext members to the shell.
> fix(overmind): match actions in ResolveAction

- packages/node_modules/overmind-react/src/index.ts
- packages/node_modules/overmind/src/Overmind.ts
Vite/rollup does not shim `global`, `process` etc which are not available in a browser (https://github.com/vitejs/vite/issues/1689).  This results in  the blocking error 'process is not defined' since the variable does not exist.
The current check for `isNode` look like this:
`const isNode = !IS_TEST && process && process.title && process.title.includes('node')`
Altering this as follows ensures this is handled properly: 
`const isNode =
!IS_TEST && typeof process !== "undefined" && process.title && process.title.includes('node')` solves this issue.
> Alter test for process

- packages/node_modules/overmind/src/index.test.ts
- packages/node_modules/overmind/src/internalTypes.ts
This allows to specify actions with optional params and calling them without a parameter, e.g.:
const actionWithOptionalParam = (context: Context, value?: string) => {
// ...
}
> feat(overmind): allow payload param of action to be optional

- packages/node_modules/overmind-statechart/src/index.ts
React's fast refresh reruns `statechart` when a module that contains this call is edited.
As the statechart was already initialized, a config error was thrown since `states` and `matches` were already present in the current state.
To avoid throwing this error, it is now only thrown when the statechart is first initialized.
> fix(overmind-statechart): avoid throwing config error when fast refresh kicks in

- packages/overmind-vue/src/vue3.ts
There is a wrong name used. It should be `proxyStateTreeInstance` instead of `proxyStateTree`
> Fix blocker bug in overmind-vue

- packages/overmind-vue/src/vue3.ts
It should be proxyStateTreeInstance, not proxyStateTree.  (this file had 2 times this typo, the first was addressed in https://github.com/cerebral/overmind/pull/521/commits/0606a7e5dcc537aca3a8c65899f1c7b47ecf5f12), this is the second one
> Fix blocker (typo error) in overmind-vue

- packages/overmind-graphql/src/index.ts
PR fixes the issue described in https://github.com/cerebral/overmind/issues/526
> fix(overmind-graphql): Add 'ReadonlyArray' interface to type 'Literals'

- packages/overmind-react/package.json
Explicitly declare React dependency, so build tools like Snowpack will use a single copy of the library. This fixes #519.
> Explicitly declare React dependency

- packages/overmind-react/src/index.ts
There is a bug while working in the development mode when components unmount: 
Minimum reproduction code: https://github.com/dopeshot/ionic-overmind-cant-perform-state-update
How to reproduce: 
1. Go to the other page
2. Increase the count (modify state)
3. Go back to main page
4. Increase the count (modify state) ==> Go to console and there is the error
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
Video of the issue: https://www.youtube.com/watch?v=5w6r1_lxoS8
StackOverflow discussion: https://stackoverflow.com/questions/70744871/ionic-react-overmind-cant-perform-a-react-state-update-on-an-unmounted- …
> Fix bug with unmounted component when working in development mode

- packages/overmind/src/Devtools.ts
- packages/overmind/src/Overmind.ts
- packages/overmind/src/internalTypes.ts
It is a bit disturbing to get a huge red error in console when starting a dev app without devtools running. A warning seems more appropriate.
> Make loglevel of "missing devtools error" configurable

- packages/node_modules/overmind-svelte/src/index.ts
Add types to `overmind-svelte` now that Svelte properly supports TypeScript.
This shouldn't change any logic, but @mfeitoza might want to review.
I hope this simple type change can make v26!
> fix(overmind-svelte): add complete typing

- packages/overmind/src/rehydrate.ts
Got an error with the newest TypeScript, this small fix seems sufficient to make it go away.
> fix: Type U does not satisfy the constraint '{}' ts(2344)
